from django.urls import path, include
from django.http import HttpResponse
from . import views
from rest_framework.routers import DefaultRouter
from .views import create_workflow, create_incident_from_audit_finding, RiskViewSet, IncidentViewSet, ComplianceViewSet, RiskInstanceViewSet, add_compliance_to_audit, get_assign_data, load_review_data, save_review_progress
from .views import framework_list, framework_detail, copy_framework, create_framework_version, export_policies_to_excel, policy_list, policy_detail, copy_policy, subpolicy_detail, create_policy_version, get_policies_by_framework, get_subpolicies_by_policy,get_subpolicies_by_policy
from .incident_counters import get_incident_counts as get_counts
# from .policy_views import get_policies_by_framework, get_subpolicies_by_policy

router = DefaultRouter()
router.register(r'risks', views.RiskViewSet)
router.register(r'incidents', views.IncidentViewSet)
router.register(r'compliances', views.ComplianceViewSet)
router.register(r'risk-instances', views.RiskInstanceViewSet)


urlpatterns = [
    # path('login/', views.login, name='login'),
    # path('register/', views.register, name='register'),
    path('', lambda request: HttpResponse("API is working ✅")),
    path('incidents/', views.list_incidents, name='list-incidents'),
    path('api/incidents/', views.list_incidents, name='api-list-incidents'),
    path('incidents/create/', views.create_incident, name='create-incident'),
    path('api/login/', views.login, name='api_login'),
    path('audit-findings/unchecked/', views.unchecked_audit_findings, name='unchecked-audit-findings'),
    path('users/', views.list_users, name='list-users'),
    path('api/users/', views.list_users, name='api-get-users'),
    path('workflow/create/', create_workflow, name='workflow-create'),
    path('workflow/assigned/', views.list_assigned_findings, name='list-assigned-findings'),
    path('dashboard/incidents/', views.combined_incidents_and_audit_findings, name='dashboard-incidents'),
    path('incident/from-audit-finding/', create_incident_from_audit_finding, name='incident_from_audit_finding'),
    path('incident/schedule-manual/', views.schedule_manual_incident, name='schedule_manual_incident'),
    path('incident/reject/', views.reject_incident, name='reject_incident'),
    path('frameworks/', framework_list, name='framework-list'),
    path('frameworks/<int:pk>/', views.framework_detail, name='framework-detail'),
    path('frameworks/<int:pk>/copy/', views.copy_framework, name='copy-framework'),
    path('frameworks/<int:pk>/create-version/', views.create_framework_version, name='create-framework-version'),
    path('frameworks/<int:framework_id>/export/', views.export_policies_to_excel, name='export-framework-policies'),
    path('policies/', views.policy_list, name='policy-list'),
    path('policies/<int:pk>/', views.policy_detail, name='policy-detail'),
    path('policies/<int:pk>/copy/', views.copy_policy, name='copy-policy'),
    path('policies/<int:pk>/create-version/', create_policy_version, name='create-policy-version'),
    path('subpolicies/<int:pk>/', subpolicy_detail, name='subpolicy-detail'),
    path('api/subpolicies/<int:pk>/', subpolicy_detail, name='api-subpolicy-detail'),
    path('api/subpolicies/<int:pk>/review/', views.submit_subpolicy_review, name='submit-subpolicy-review'),
    path('api/subpolicies/<int:pk>/resubmit/', views.resubmit_subpolicy, name='resubmit-subpolicy'),
    path('api/frameworks/<int:framework_id>/policies/', views.add_policy_to_framework, name='add-policy-to-framework'),
    path('api/frameworks/<int:framework_id>/get-policies/', get_policies_by_framework, name='get-policies-by-framework'),
    path('api/policies/<int:policy_id>/get-subpolicies/', get_subpolicies_by_policy, name='get-subpolicies-by-policy'),
    path('api/policy-approvals/reviewer/', list_policy_approvals_for_reviewer, name='policy-approvals-for-reviewer'),
    path('api/policy-approvals/', views.list_all_policy_approvals, name='list-all-policy-approvals'),
    path('api/policy-approvals/<int:approval_id>/', views.update_policy_approval, name='update_policy_approval'),
    path('api/policy-approvals/<int:approval_id>/review/', views.submit_policy_review, name='submit_policy_review'),
    path('api/policy-approvals/rejected/<int:user_id>/', views.list_rejected_policy_approvals_for_user),
    path('api/policy-approvals/resubmit/<int:approval_id>/', views.resubmit_policy_approval),
    path('api/frameworks/', views.framework_list, name='api-frameworks'),
    path('api/frameworks/<int:pk>/', views.framework_detail, name='api-framework-detail'),
    path('api/policies/', views.policy_list, name='policy-list-with-status'),
    path('api/frameworks/<int:framework_id>/policies/', views.add_policy_to_framework, name='add-policy-to-framework'),
    path('api/frameworks/<int:framework_id>/subpolicies/', views.get_subpolicies, name='get-subpolicies'),
    path('compliance/create/', views.create_compliance, name='create-compliance'),
    path('compliance/<int:compliance_id>/edit/', views.edit_compliance, name='edit-compliance'),
    path('compliance/<int:compliance_id>/clone/', views.clone_compliance, name='clone-compliance'),
    path('compliance/dashboard/', views.get_compliance_dashboard, name='compliance-dashboard'),
    path('api/compliance-approvals/<int:approval_id>/review/', views.submit_compliance_review, name='submit_compliance_review'),
    path('api/compliance-approvals/resubmit/<int:approval_id>/', views.resubmit_compliance_approval, name='resubmit_compliance_approval'),
    path('test-connection/', views.test_connection, name='test-connection'),
    path('api/', include(router.urls)),
    path('api/last-incident/', views.last_incident, name='last-incident'),
    path('api/compliance-by-incident/<int:incident_id>/', views.get_compliance_by_incident, name='compliance-by-incident'),
    path('api/risks-by-incident/<int:incident_id>/', views.get_risks_by_incident, name='risks-by-incident'),
    path('api/analyze-incident/', views.analyze_incident, name='analyze-incident'),
    path('api/risk/metrics', views.risk_metrics, name='risk_metrics'),
    path('api/risk-workflow/', views.risk_workflow, name='risk-workflow'),
    path('api/risk-assign/', views.assign_risk_instance, name='risk-assign'),
    path('api/custom-users/', views.get_custom_users, name='custom-users'),
    path('api/user-risks/<int:user_id>/', views.get_user_risks, name='user-risks'),
    path('api/risk-update-status/', views.update_risk_status, name='risk-update-status'),
    path('api/risk-mitigations/<int:risk_id>/', views.get_risk_mitigations, name='risk-mitigations'),
    path('api/update-mitigation-status/', views.update_mitigation_approval, name='update-mitigation-status'),
    path('api/assign-reviewer/', views.assign_reviewer, name='assign-reviewer'),
    path('api/reviewer-tasks/<int:user_id>/', views.get_reviewer_tasks, name='reviewer-tasks'),
    path('api/complete-review/', views.complete_review, name='complete-review'),
    path('api/reviewer-comments/<int:risk_id>/', views.get_reviewer_comments, name='reviewer-comments'),
    path('api/latest-review/<int:risk_id>/', views.get_latest_review, name='latest-review'),
    path('api/get-assigned-reviewer/<int:risk_id>/', views.get_assigned_reviewer, name='get-assigned-reviewer'),
    path('api/risk-update-mitigation/<int:risk_id>/', views.update_risk_mitigation, name='risk-update-mitigation'),
    path('assign-data/', get_assign_data, name='get_assign_data'),
    path('allocate-policy/', views.allocate_policy, name='allocate_policy'),
    path('audits/', views.get_all_audits, name='get_all_audits'),
    path('my-audits/', views.get_my_audits, name='get_my_audits'),
    path('my-reviews/', views.get_my_reviews, name='get_my_reviews'),
    path('audits/<int:audit_id>/', views.get_audit_details, name='get_audit_details'),
    path('audits/<int:audit_id>/status/', views.update_audit_status, name='update_audit_status'),
    path('audits/<int:audit_id>/review-status/', views.update_review_status, name='update_review_status'),
    path('audits/<int:audit_id>/get-status/', views.get_audit_status, name='get_audit_status'),
    path('audits/<int:audit_id>/compliances/', views.get_audit_compliances, name='get_audit_compliances'),
    path('audits/<int:audit_id>/submit/', views.submit_audit_findings, name='submit_audit_findings'),
    path('audits/<int:audit_id>/versions/<str:version>/', views.get_audit_version_details, name='get_audit_version_details'),
    path('audits/<int:audit_id>/check-version/', views.check_audit_version, name='check_audit_version'),
    path('audit-findings/<int:compliance_id>/', views.update_audit_finding, name='update_audit_finding'),
    path('audit-findings/<int:compliance_id>/upload-evidence/', views.upload_evidence, name='upload_evidence'),
    path('compliance/', views.get_all_compliance, name='get_all_compliance'),
    path('subpolicies/<int:subpolicy_id>/compliance/', views.get_compliance_by_subpolicy, name='get_compliance_by_subpolicy'),
    path('audits/<int:audit_id>/add-compliance/', add_compliance_to_audit, name='add_compliance_to_audit'),
    path('add-majorminor-column/', views.add_majorminor_column, name='add_majorminor_column'),
    path('fix-subpolicy-version/', views.fix_subpolicy_version_field, name='fix_subpolicy_version_field'),
    path('audits/<int:audit_id>/save-review/', save_review_progress, name='save_review_progress'),
    path('audits/<int:audit_id>/load-review/', load_review_data, name='load_review_data'),
    path('api/incident/mttd/', views.incident_mttd, name='incident-mttd'),
    path('api/incident/mttr/', views.incident_mttr, name='incident_mttr'),
    path('api/incident/mttc/', views.incident_mttc, name='incident-mttc'),
    path('api/incident/mttrv/', views.incident_mttrv, name='incident-mttrv'),
    path('api/incident/first-response-time/', views.first_response_time, name='first-response-time'),
    path('api/incident/escalation-time/', views.escalation_time, name='escalation-time'),
    # path('api/incident/incidents-detected/', views.incident_volume, name='incidents-detected'),
    path('api/incident/incident-volume/', views.incident_volume, name='incident-volume'),
    path('api/incident/escalation-rate/', views.escalation_rate, name='escalation-rate'),
    path('api/incident/repeat-rate/', views.repeat_rate, name='repeat-rate'),
    path('api/incident/metrics/', views.incident_metrics, name='incident-metrics'),
    path('api/incidents/counts/', views.get_incident_counts, name='incident-counts'),
    path('api/frameworks/<int:framework_id>/get-policies/', get_policies_by_framework, name='get-policies-by-framework'),
    path('api/policies/<int:policy_id>/get-subpolicies/', get_subpolicies_by_policy, name='get-subpolicies-by-policy'),
    path('api/incident/count/', views.incident_count, name='incident-count'),
    path('api/incident/by-severity/', views.incidents_by_severity, name='incidents-by-severity'),
    path('api/incident/root-causes/', views.incident_root_causes, name='incident-root-causes'),
    path('api/incident/origins/', views.incident_origins, name='incident-origins'),
    path('api/incident/types/', views.incident_types, name='incident-types'),
    path('api/incident/incident-cost/', views.incident_cost, name='incident-cost'),
    path('api/incident/cost/', views.incident_cost, name='incident-cost-alt'),
]


 
 