# Generated by Django 5.2.1 on 2025-05-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignee', models.IntegerField()),
                ('auditor', models.IntegerField()),
                ('assigned_date', models.DateTimeField()),
                ('duedate', models.DateField()),
                ('frequency', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
                ('completion_date', models.DateTimeField(null=True, blank=True)),
                ('reviewer', models.IntegerField()),
                ('framework_id', models.IntegerField()),
                ('policy_id', models.IntegerField()),
                ('review_status', models.CharField(max_length=45, null=True, blank=True)),
                ('auditcol', models.BooleanField(default=False)),
                ('reviewer_comments', models.CharField(max_length=255, null=True, blank=True)),
                ('audit_type', models.CharField(choices=[('I', 'Internal'), ('E', 'External')], max_length=1)),
                ('reports', models.JSONField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('FrameworkId', models.AutoField(primary_key=True, serialize=False)),
                ('FrameworkName', models.CharField(max_length=255)),
                ('Version', models.CharField(max_length=50)),
                ('FrameworkDetails', models.TextField()),
                ('Date', models.DateField()),
                ('CreatedByName', models.CharField(max_length=255)),
                ('CreatedByDate', models.DateField()),
                ('AuthorisedByName', models.CharField(max_length=255)),
                ('AuthorisedByDate', models.DateField()),
                ('Category', models.CharField(max_length=50)),
                ('DocURL', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('FrameworkId', models.IntegerField()),
                ('PolicyId', models.AutoField(primary_key=True, serialize=False)),
                ('Version', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('PolicyDetails', models.TextField()),
                ('PolicyName', models.CharField(max_length=255)),
                ('EffectiveStartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Department', models.CharField(max_length=255)),
                ('CreatedByName', models.CharField(max_length=255)),
                ('CreatedByDate', models.DateField()),
                ('AuthorisedByName', models.CharField(max_length=255)),
                ('AuthorisedByDate', models.DateField()),
                ('Applicability', models.CharField(max_length=255)),
                ('DocURL', models.CharField(max_length=255)),
                ('scope', models.TextField()),
                ('objective', models.TextField()),
                ('frequency', models.IntegerField()),
                ('identifier', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
                ('MobileNo', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField()),
                ('UpdatedAt', models.DateTimeField()),
                ('role', models.CharField(max_length=45)),
                ('branch', models.CharField(max_length=45)),
            ],
        ),
    ]
