# Generated by Django 5.2.1 on 2025-06-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0003_update_audit_table'),
        ('grc', 'add_majorminor_to_auditfindings'),
    ]

    operations = [
    ]
