# Generated by Django 5.2.1 on 2025-06-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0002_add_report_to_audit'),
        ('grc', '0004_merge_20250601_0912'),
    ]

    operations = [
    ]
