# Generated by Django 5.2.1 on 2025-06-02 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0004_merge_20250601_0912'),
        ('grc', '0005_merge_20250601_2321'),
    ]

    operations = [
    ]
